kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
    name: $Cluster
    region: us-east-1

nodeGroups:
  - name: base
    minSize: 1
    desiredCapacity: 1
    maxSize: 1
    instancesDistribution:
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
    iam:
      withAddonPolicies:
        autoScaler: true 

  - name: spot
    minSize: 1
    maxSize: 1
    instancesDistribution:
      maxPrice: 0.0035
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 1
    iam:
      withAddonPolicies:
        autoScaler: true 
